server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  application:
    name: service-registry

eureka:
  instance:
    hostname: web-production-f0db0.up.railway.app
    prefer-ip-address: false

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://web-production-f0db0.up.railway.app/eureka/