server:
  port: ${PORT:8081}
  address: 0.0.0.0

spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      routes:
        - id: oauth2
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/oauth2/**, /login/**

        - id: auth-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/users/**
          filters:
            - JwtFilter

        - id: qma-service
          uri: ${QMA_SERVICE_URL}
          predicates:
            - Path=/api/**
          filters:
            - JwtFilter

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - ${FRONTEND_URL}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}